### ISSUE TITLE
No "You did not enter a valid expression" when using adaptive marking

### ISSUE THREAD

**Issue by Spruce8913** [numbas/Numbas#1068]
Typically when one tries to submit an empty answer, there's a brown popup with a reminder that "You did not enter a valid number/expression/...". In this example question, with two parts, each with a gapfill with a single gap, no popup is shown.
![image](https://github.com/numbas/Numbas/assets/49608009/9c7574cf-8848-4626-8347-a6cffeaee470)
The first gap asks for a number, second gap asks for mathematical expression with adaptive marking using the first gap. For the adaptive marking, "always replace variables" and "must be answered" for the previous part is ticked on.

After some experimenting, I found the warning is included on the bottom right:
![image](https://github.com/numbas/Numbas/assets/49608009/e259f7b3-e785-4c67-a78d-ed2768b9c27e)
And also if "must be answered" is not ticked on, the warning is included in the same way:
![image](https://github.com/numbas/Numbas/assets/49608009/a7df3cea-3cf1-44f6-8a65-97933f8abea8)

Would it be possible to give these warning messages the same layout as the others? This way students ask for help during the exam, rather than afterwards being unhappy about their grade.

**Comment by christianp** [comment]
Can you give me a link to this question in the editor, please?

**Comment by christianp** [comment]
There is indeed an error here, and Numbas is doing the right thing to show it.
In the gap-fill part b, you have adaptive marking set to replace the value of `x0` with the answer to part a. Part a is a gap-fill, so its answer value will be a list. `x0` is used in the definition of `y0`, so the error first occurs when trying to multiply `x0` by a number.

There's also a warning in the editor that since you've replaced `x0`, `y0` will be re-evaluated, and since its definition includes some randomisation you'll end up with inconsistent values.

Since part a is being used to replace both `x0` in the gap-fill, and `slope` in the mathematical expression gap, there's definitely an authoring error in your example.

After fixing that, I see your point about the warning box when "must be answered?" is ticked. I'll make it also show the warning next to the input box.
