### ISSUE TITLE
Steps with marked questions and Information only parts 

### ISSUE THREAD

**Issue by BillFoster** [numbas/Numbas#258]
Information only parts have 0 marks. But you can include Steps with an Information only part and the Steps can have a type which has marks allocated to it. It may be a good idea to allow such questions with an Information only part, to gain insight or to allow students to answer questions without prejudice - not altogether sure. This would be OK as on testing the marks that may be gained from answering such a Steps question are not counted in the final tally - but the students should be warned that any marks so gained are not counted at all in the final mark for the question.

**Comment by christianp** [comment]
In formative mode, the marks are for the student's benefit, and it doesn't really matter what the total is. 
I can't see why you'd want to do this (optional marked bits that don't count towards the total) in assessed mode. 

I just made a test question using a number entry part instead of an information only part (https://numbas.mathcentre.ac.uk/question/7111/issue-258-optional-steps-in-a-part-with-no-marks/), and I was surprised that I didn't get any feedback for the part worth 0 marks. So maybe a solution is that parts with zero marks should show feedback? That question shows a problem with there being no feedback - it's not completely clear where the three marks awarded for the steps go when counting up the total for the question.
