### ISSUE TITLE
Raise Numbas internal precision for conversion to fractions

### ISSUE THREAD

**Issue by WoosterUK** [numbas/Numbas#431]
See question : https://numbas.mathcentre.ac.uk/question/7408/math0380-gp2/

The question amounts to evaluating sum(map(1/a^n,n,n1..n2)), with n1 currently fixed equal to 1. Now, Numbas freaks out a bit when a = 4, n2 = 11. (Note that the question code has been altered to prevent n2 = 11.) The correct answer is 1398101/4194304 in lowest terms, or 4194303/12582912 as the answer formula would calculate. Numbas will mark 1/3 as incorrect perfectly happily, but having been told to report the correct answer as a fraction, reports the correct answer as... 1/3.

I'm guessing there must be a cost-benefit analysis to raising the precision level, but could you look at whether https://github.com/numbas/Numbas/blob/master/runtime/scripts/math.js#L1472 could be set to something bigger than 15 (which leads to a precision of about 3e-7 in decimal)?

**Comment by christianp** [comment]
Crikey! 
The precision is set that low because I was worried that most of the time, a difference on the order of 1e-8 is the result of accumulated rounding error, so you probably want to show a fraction with a smaller  denominator. That comes unstuck when the "expected answer" is marked incorrect because it's not the _real_ expected answer.
We want to ensure that we get a fraction lying between the minvalue and maxvalue. My first thought is to pick the accuracy based on the absolute difference between minvalue and maxvalue. I've just implemented that now on my dev server and it looks like it works for your question, but I feel like I need to do deeper thinking about it. 
A final wrinkle is that the number entry part has a built-in "fudge" error of 0.00000000001, applied to the minvalue and maxvalue, again to combat rounding problems. I'm very reluctant to change that, because once you get down to that precision you're almost bound to bump into floating point errors as soon as you do anything.
If you want really really big denominators, you might be better off changing the part to a "mathematical expression" type, and either setting the checking accuracy really low or even looking at the student's answer as a syntax tree.

**Comment by WoosterUK** [comment]
Math expression: why didn't I think of that! Okay, thanks, I'll have a look at that.
