### ISSUE TITLE
A simplification rule to deal with products of pi and a fraction

### ISSUE THREAD

**Issue by vegardl** [numbas/Numbas#441]
Hi,

I wanted to use \simplfy[collectNumbers,fractionNumbers] to get nice answers like pi/3
when I came across this. Numbas sometimes think that e and pi are rational numbers
that should be simplified as part of the fraction and sometimes not.
If you define a variable a = 1/3, then pi_a gives a fraction while pi_1/3 does not. See:
[https://numbas.mathcentre.ac.uk/question/13476/simplify-collectnumbers-and-fractionnumbers/](https://numbas.mathcentre.ac.uk/question/13476/simplify-collectnumbers-and-fractionnumbers/)

**Comment by christianp** [comment]
The `collectNumbers` rule only collects together addition, subtraction and multiplication of numbers - not division. 

When you write `pi*{1/3}`, the `{1/3}` is evaluated to the decimal `0.3333333333...`, which `collectNumbers` will multiply by `pi`. Once it's done that, the code to pick out factors of pi only looks for integer multiples, so it just gives the rational approximation `355/339` instead.

However, `pi*1/3` is only simplified to `pi/3` - it doesn't do the division. That's why, in your example `e*2/3`, the `e*2` is collected together, and then the code doesn't look for multiples of e so you get `(5442/1001)/3`.

I'm not sure what to do about this. I'm wary of expanding the "pick out factors of pi" code to look for fractions, because it'll make false positives much more likely. Maybe I could add a new rule called something like `fractionPi` which spots numbers of the form `{pi*a/b}`, where b is small, and rewrites them as `{pi*a}/b`.

**Comment by vegardl** [comment]
OK, thanks. I see now that is was my expectations that were faulty.
A workaround is then to protect pi with division. With b=6 and c=2
I can get pi/3 by using: {pi/{b/c}}

**Comment by christianp** [comment]
I don't think this is worth doing - it'd be too unpredictable.
