### ISSUE TITLE
Add an option to shuffle question groups

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#525]
At the moment, you can ask for the questions inside question groups to appear in a random order, but you can't do the same with question groups themselves. You might want to do this so that you don't always get a question on the same topic at the start of the exam.

To do this:

* In [`bin/exam.py`](https://github.com/numbas/Numbas/blob/master/bin/exam.py#L119), add a field `shuffleQuestionGroups` and make sure it's loaded in `fromDATA` and output in `toxml`.
* In [`runtime/scripts/exam.js`](https://github.com/numbas/Numbas/blob/master/runtime/scripts/exam.js#L388), change `chooseQuestionSubset` so it shuffles the groups, if necessary. You'll also need to change the `load` method to restore the order of the groups, which will probably also involve changing `setSuspendData` in [`runtime/scripts/scorm-storage.js`](https://github.com/numbas/Numbas/blob/master/runtime/scripts/scorm-storage.js#L297) to save the order of the question groups. Checking this works will require running an exam inside a SCORM player - I can do this if it's too much effort.

**Comment by artemdou** [comment]
Hi, I would like to work on this issue

**Comment by christianp** [comment]
@artemdou Thanks! Please have a look at [our guidelines on contributing to Numbas](https://www.numbas.org.uk/contributing-to-numbas/#contributing-code)

**Comment by artemdou** [comment]
Hi, I've been working on this issue for a while now but something is going wrong when I test whether it is able to load or not and I can't seem to fix it. I changed the [chooseQuestionSubset](https://github.com/artemdou/Numbas/blob/15c44925507129e934b564d0898518dad08425f1/runtime/scripts/exam.js#L413), [makeQuestionList](https://github.com/artemdou/Numbas/blob/15c44925507129e934b564d0898518dad08425f1/runtime/scripts/exam.js#L438), and [load ](https://github.com/artemdou/Numbas/blob/15c44925507129e934b564d0898518dad08425f1/runtime/scripts/exam.js#L372)methods in runtime/scripts/exam.js as well as the [initQuestionList ](https://github.com/artemdou/Numbas/blob/15c44925507129e934b564d0898518dad08425f1/themes/default/files/scripts/exam-display.js#L270)in themes/default/files/scripts/exam-display.js and thought the shuffling is working fine when I exit the test and try to reload it, it shows me the loading bar but never the actual test.
Do you have any idea what is going wrong because I can't think of where the problem may occur?

**Comment by christianp** [comment]
@artemdou thanks for sticking with this! If you make a pull request, I can look at your code and find the problem.

**Comment by artemdou** [comment]
@christianp Hi, as you may have seen I already made a pull request in this repository and it seems to be working fine so I started changing the [editor repository](https://github.com/EVratsanou/editor), adding a suffleQuestionGroups field and I come across this error 

> Unable to process binding "checked: function(){return shuffleQuestionGroups }"
Message: shuffleQuestionGroups is not defined

The new field is modeled after the showQuestionGroupNames property so I don't understand what I am missing. If you could take a look and give me some direction I would really appreciate it

**Comment by christianp** [comment]
@artemdou for the problem with the editor: if you're inside a `foreach` block, you might need to use `$parent.shuffleQuestionGroups`.
