### ISSUE TITLE
SCORM and Moodle numbers screwed

### ISSUE THREAD

**Issue by rojizo** [numbas/Numbas#575]
On the current moodle of my university (it seems to be moodle 3.5) we have the following problem. When the answer is saved on the moodle side, the fractions introduced by the students get saved as NaN. Probably Numbas is telling moodle that is is a number and sending a the fraction and Moodle tries to parse it as a floating point number and... bang! This should be recorded always as texts

**Comment by christianp** [comment]
Thanks for reporting this. The problem was that the code to save the student's answer for a number entry part was running it through `Numbas.math.niceNumber`, which assumes its input is a number. Since Numbas v3.0, the `studentAnswer` property is the exact string the student typed, so `niceNumber` doesn't cope with fractions, and is unnecessary anyway.

This could have caused some nasty problems - thanks very much for the report!
