### ISSUE TITLE
Should the JSXgraph extentsion be in its own repository?

### ISSUE THREAD

**Issue by JoshuaCapel** [numbas/Numbas#591]
It seems a lot of the Numbas extensions are in their own github repositories (e.g. https://github.com/numbas/numbas-extension-quantities). However the JSXgraph extension is part of the numbas runtime repository (current located in https://github.com/numbas/Numbas/tree/master/extensions/jsxgraph). 

For several week I was under the impression it was not a publicly available extension, because I could easily find the rest in their own repos. Moving it to it's own repo might clear up future confusion.

**Comment by christianp** [comment]
You're right, I should move both it and the stats extension to their own repos.

**Comment by christianp** [comment]
I've moved jsxgraph to [numbas/numbas-extension-jsxgraph](https://github.com/numbas/numbas-extension-jsxgraph) and stats to [numbas/numbas-extension-stats/](https://github.com/numbas/numbas-extension-stats/). I've also removed the other built-in extensions, because they almost definitely don't work any more, and as far as I know have never been used.
