### ISSUE TITLE
Number entry part: allow fractions and apply a precision restriction

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#604]
It should be possible to tick "allow the student to enter a fraction" and select a decimal places or significant figures restriction at the same time.
If the student enters a fraction, the min and max values are unmodified. If they enter a decimal, the min and max values are rounded to the student's precision and the penalty is applied if the student's answer is not given to the required precision.

This feels iffy, because for example `2/3` and `0.67` are not the same thing, but in a less rigorous applied context I can see why you'd want to accept either.

**Comment by zaript** [comment]
Perhaps consider more general approach - allow for multiple different marking passes, while keeping each pass relatively simple?
I often want to apply a very restrictive pattern first, and then still give a partial mark for the correct answer in the wrong form. Rather than trying to fit in the same interface, maybe just allow for more than one marking approaches to be defined. If the first one passes, then consequent ones are ignored. If the first one fails, second one applied, and so on.

**Comment by christianp** [comment]
That kind of thing is on my plan for the next few months! My idea is to allow you to create alternative versions of a part, changing only the marking settings. The student would get the feedback from the version that gives the most credit.

**Comment by christianp** [comment]
This is handled by alternative answers, and I don't think it's sufficiently common that it should be part of the main settings.
