### ISSUE TITLE
Missing Units Equivalency

### ISSUE THREAD

**Issue by gordonsmithwkuedu** [numbas/Numbas#610]
In a "Quantity with Units" question (Entropy generation through a wall), Numbas does not seem to recognize that a Watt (W) is the same as a Joule per second (J/s), so students are being incorrectly penalized.

This would also apply to modified units (kW = kJ/s, etc)

**Comment by christianp** [comment]
I've made a question where the answer is 3W. Both `3W` and `3J/s` are accepted.
In your question, is "What to do if different units used" set to "Convert", or something else?

**Comment by gordonsmithwkuedu** [comment]
It is set to convert.  The correct unit for what we’re targeting would be W/degK.  An equivalent unit would be J/s/degK or other variations

**Comment by christianp** [comment]
Ahh, that's because of the way it parses the units. It accepts `J/s*degK`, but not `J/s/degK`.
It looks like it's set up to accept strings of the form `a*b*c / d*e*f`, where anything to the left of the slash is the numerator and to the right is the denominator. Under the normal order of operations, you'd expect some brackets.
`J/s/degK` is how I'd write it, so I have some work to do.

**Comment by christianp** [comment]
I've updated the parsing code so units in the denominator can be joined by `/`. `J/s/degK` is now correctly parsed, and is equivalent to `W/degK`. Please check that your question works and close this issue if so.

**Comment by gordonsmithwkuedu** [comment]
Looks great!  Thanks!
