### ISSUE TITLE
Item added to basket: colour accessibility 

### ISSUE THREAD

**Issue by joshualim** [numbas/Numbas#627]
The shopping cart icon moves from dark blue to dark green when selecting a question: this is a subtle change. Consider instead:
- two colours with more differing contrast 
- or better still, have the icon change

**Comment by christianp** [comment]
Very good point. I've never found it easy to differentiate them, but I've never done anything about it. I've labelled this "good first issue", because it's easy to fix.

We use the glyphicons provided by Bootstrap, which only has one shopping cart icon, but we could easily use a couple of custom-made icons.

**Comment by ShraddheyaS** [comment]
Hi, I'd like to take this up. I realise that the [update_basket](https://github.com/numbas/editor/blob/87c4f531d05cfb1f2e265b325071cb740902fa91/editor/static/js/editor.js#L2068) function needs to be updated to change the effect of a particular question being present in the basket. 
Is there a specific icon (custom-made or otherwise) that we are looking for, or a simple transition to "glyphicon glyphicon-thumbs-up" would also work?

**Comment by christianp** [comment]
@ShraddheyaS I think we need a new icon, which still has a basket. The thumbs up icon makes sense in the instant that you press the button, but later on has no obvious meaning.

**Comment by christianp** [comment]
I've changed the display to show the icon in white on a coloured background when the item is in the basket. It's a simple fix without making a new icon. I'm closing this now, but if anyone comes up with a pair of icons I'll happily use them.
I've also made it update the title text, so you can tell by hovering over or screen-reading the button which state it's in.
