### ISSUE TITLE
Lockouts on revealing answers

### ISSUE THREAD

**Issue by gordonsmithwkuedu** [numbas/Numbas#638]
Gave a test today, and had a quirk reveal itself...

A student tried Part 1 of the problem (Determining radius of curvature from g-forces (translational kinematics question)), and decided to go for the steps (sacrificing half their points).  They successfully completed all the steps, and unthinkingly hit "reveal answer" _before_ hitting "submit" with the result that all the correct steps got invalidated (even though they'd been marked correct on an individual basis) and they received no credit for the work.  Is there a "are you sure" validation or some other doublecheck to see if there are entries that haven't been recorded warning?  I didn't see the warnings he did get, there may already be something in place, and he just breezed by them...

**Comment by gordonsmithwkuedu** [comment]
I can reproduce it on the deployed SCORM zip file. 

The problem loads, I ask to see the steps.  I enter all the (correct) answers, but never hit "submit" on any of them.  If I ask to see the answers at this point, the entries in the individual steps are cleared, and no credit is issued even though the answers match what was in the box (because the system, presumably, never saw what was in the box).

**Comment by christianp** [comment]
Could you email the zip file to numbas@ncl.ac.uk, please?

**Comment by christianp** [comment]
Oh, if you never hit submit, that's the intended behaviour. You said that the steps had been marked correct, which only happens when the corresponding "submit" buttons are pressed.

We have an open issue (#545) about a "submit automatically" feature. There are some complications I can foresee, if we ever have a situation where submitting a wrong answer is worse for the student than submitting nothing at all. For now though, maybe it makes sense to automatically submit before reveal or at the end of the exam.
