### ISSUE TITLE
Displaying Steps

### ISSUE THREAD

**Issue by gordonsmithwkuedu** [numbas/Numbas#640]
In some cases, it is possible to have so many steps to a problem that you lose track of the problem state waaaaaaaay at the top.  Is it possible to split the screen into two windows, with the problem statement at the left, and the scrollable steps to the right?  Or the problem at the top and the scrollable steps below?

**Comment by christianp** [comment]
I don't think that would be a good solution, because down the line I'll get people putting information as the first step, and asking for it to be visible while answering the last step. Split screens don't work well on mobile, either.

I think this is a problem for the question author - think about how you can restructure the question, or repeat key information.
