### ISSUE TITLE
htmlAttached: accessing html in parts.

### ISSUE THREAD

**Issue by ugonj** [numbas/Numbas#711]
In Numbas 3, when calling htmlAttached I could access the html from the parts prompt, which I used to hide some elements. This doesn't seem possible any longer in Numbas 4.

The example given in the documentation:

```javascript
question.signals.on('HTMLAttached',function() {
    question.display.html.find('.statement #secret').hide();
});
```

fails with the error: `TypeError: question.display.html.find is not a function`.

Replacing `find` with `querySelector`:

```javascript
question.signals.on('HTMLAttached',function() {
    console.log(question.display.html.querySelector('.statement #secret'));
});
```
shows the element `#hide` if it is in the question statement, but returns `null` if it is in the part prompt.

Here is a link to a question showing this behaviour:
https://numbas.mathcentre.ac.uk/question/share/edit/718371ca-c65a-49d2-86c0-52fbbc4a4ca2

**Comment by christianp** [comment]
Thanks for reporting this. It broke in Numbas 5, since part HTML is now generated separately to the rest of the question HTML.

I've fixed the documentation - the `question.display.html` needed to be wrapped in jQuery `$()`, so it now reads `$(question.display.html).find('.statement #secret').hide()`.

The `HTMLAttached` signal is now only triggered once all the parts have had their HTML generated. Parts now also have a signal box, so you can do

```
question.getPart('p0').signals.on('HTMLAttached',function() {
   ...
})
```

**Comment by ugonj** [comment]
Fantastic! Thank you @christianp A HTMLAttached signal for each part is actually nice, as it gives greater control.
