### ISSUE TITLE
Edit extension link is wrong

### ISSUE THREAD

**Issue by philcolbourn** [numbas/Numbas#718]
From profile select Extensions - 'Edit this extension' has incorrect URL:

https://numbas.mathcentre.ac.uk/extensions/###/edit

Link should be:

https://numbas.mathcentre.ac.uk/extensions/###/edit_source

Same URL error on Extensions and Scripts division of a question to edit an Extension.

**Comment by christianp** [comment]
I'm not sure this is strictly incorrect - that page does exist for all extensions, while the "edit source" one doesn't for extensions installed locally on the server.

It looks like the real problem is that the extension's files aren't listed in the sidebar on that page. I'll fix that, then close this issue.

**Comment by philcolbourn** [comment]
ta. I think I raised issue in wrong place...

Yes, extension files don't show up as you say.
