### ISSUE TITLE
Variable testing issue/question

### ISSUE THREAD

**Issue by ugoertz** [numbas/Numbas#777]
If a variable testing condition involves a variable that depends on another one via a custom JME function (in "Extensions and Scripts"), then the test condition cannot be evaluated. See [this question](https://numbas.mathcentre.ac.uk/question/81692/variable-testing-issue-question/) for a simple example.

As far as I can see, when the test is run, the dependency on the "other" variable (`b` in the example question) is not picked up (maybe this is actually intended behavior - I suppose that digging through all JME custom functions is not really somethings one wants to do, so the alternative would be to always provide all variables(?)).

The problem disappears if `b` occurs in the definition of `a` (say I define `a` as `0*b + gr()`). Another way to avoid it is to pass `b` as a parameter to the JME function (maybe this is the "official" way to go?). I am confused however that the issue shows even though `b` itself occurs in the testing condition - I might be misunderstanding how this is supposed to work.

**Comment by christianp** [comment]
I think the easiest thing technically is to not allow references to external variables inside function definitions.
But I can totally see why you'd want to do this, so I'm inclined to make it work, and live with the consequences. The problem is that the `Numbas.jme.findvars` method doesn't pick up free variables in the definition of a custom JME function, so it can't work out that `b` needs to be evaluated before your function can be called.
I've added some code to `makeJMEFunction` that makes it detect these references, so your example now works.
