### ISSUE TITLE
Recognising equivalent forms of trigonometric powers 

### ISSUE THREAD

**Issue by Tarang74** [numbas/Numbas#844]
I have an issue with a quiz answer: 
```js
sec^2(theta) // Correct answer
```
I tried:
```js
1. sec(theta)^2 // Marked incorrect
```
which was incorrect, but I understand writing a power like that is ambiguous, so I tried:
```js
2. (sec(theta))^2 // Marked incorrect even though it should be correct
```
instead, which was surprisingly also marked as incorrect.

Does the parser not recognise that the second form is equivalent to the correct answer?

**Comment by christianp** [comment]
Hi, Numbas doesn't recognise the `sec^2(theta)` notation as equivalent to `sec(theta)^2`, by design. It's inconsistent with other uses of superscripts. Numbas interprets `sec^2(theta)` as `sec^2 * theta`.
We have an open issue at #478 about whether to allow this notation as an option.
There's a page describing the problems with the notation at https://whystartat.xyz/wiki/Powers_of_trigonometric_functions.

**Comment by Tarang74** [comment]
Thanks @christianp so do you recommend only using (sin(theta))^2 from here onwards?

**Comment by christianp** [comment]
@Tarang74 yes, that's what I'd use.
