### ISSUE TITLE
Only several questions are shown when user printed the exam transcript as pdf

### ISSUE THREAD

**Issue by anggalol** [numbas/Numbas#901]
One solution to solve this problem is users need to scale down the text. But that was annoying

**Comment by encomer** [comment]
Hi @anggalol . I experienced the same problem, using Windows 10, and Chrome browser.
The following two PDF are from a very simple exam: the first is at normal (100%) scale, and the second is 70% scale.
[X-t22-1 - preview - Numbas at mathcentre.ac.uk-100percent.pdf](https://github.com/numbas/Numbas/files/8413700/X-t22-1.-.preview.-.Numbas.at.mathcentre.ac.uk-100percent.pdf)
[X-t22-1 - preview - Numbas at mathcentre.ac.uk-70percent.pdf](https://github.com/numbas/Numbas/files/8413699/X-t22-1.-.preview.-.Numbas.at.mathcentre.ac.uk-70percent.pdf)
In larger (typical) exams, I have to use about 50% of the normal scale, or even less.

**As a reference**: I've an stand-alone exam, generated by _march, 2nd. and it works fine_. But if I test-run the same exam in the current Numbas editor, then the problem that you are reporting, appears again. 

My current "solution" is to divide my normal exam in several one-question exams. But I hope we can find a solution to this problem, especially because I'm currently using the stand-alone exam mode.

**Thank you in advance to any member of the development team, for your support concerning this issue**.

Best regards,
Enrique Comer

**Comment by christianp** [comment]
It looks like this was a result of a recent change where I noticed that 'invisible' elements were still affecting the page layout.
I've made another change, and checked that everything that should be shown in print view, is shown. Thanks for reporting this!

**Comment by encomer** [comment]
Hello Christian:

Thank you very much for the good news about this issue.I did a test with my exams, and now the PDF preview is working fine.
Congratulations for all your great work on the Numbas editor.

Best regards,Enrique Comer

    On Tuesday, April 5, 2022, 01:06:36 AM PDT, Christian Lawson-Perfect ***@***.***> wrote:  
 
 


It looks like this was a result of a recent change where I noticed that 'invisible' elements were still affecting the page layout.
I've made another change, and checked that everything that should be shown in print view, is shown. Thanks for reporting this!
