### ISSUE TITLE
display of a fraction with 0 in the numerator

### ISSUE THREAD

**Issue by BillFoster** [numbas/Numbas#91]
an expression such as \simplify[std]{-{a}/{b}} where std includes the rules  all and fractionNumbers is displayed as -0 if a=0
OK if  \simplify[std]{{-a}/{b}}, then displayed as 0

**Comment by christianp** [comment]
The problem is that there's no rule rewriting `-0` to `0`. Nothing to do with fractions! The reason the second one doesn't have the problem is that it evaluates `-a`, and internally `-0` is the same number as `0`. In the first case, we have the negation operator applied to the number 0, as an expression.

I need to add a simplification rule which rewrites `-0` to `0`.
